#!/bin/bash
# Builds Backrooms.saver (plus the backdev harness) with the Command Line Tools
# only. No Xcode project, no Metal offline toolchain: the shader is embedded as
# source and compiled by the Metal runtime at launch.
set -euo pipefail

cd "$(dirname "$0")"
ROOT="$PWD"
BUILD="$ROOT/build"
TARGET="arm64-apple-macos13.0"
INSTALL_DIR="$HOME/Library/Screen Savers"
NAME="Backrooms"
CLASS="BackroomsSaverView"

mkdir -p "$BUILD"

# ---------------------------------------------------------------------------
# 1. Embed the .metal source into one Swift string literal
# ---------------------------------------------------------------------------
GEN="$BUILD/ShaderSource.swift"
{
  echo "// Generated by build.sh from the project's .metal files - do not edit."
  echo 'let kShaderSource = #"""'
  cat "$ROOT"/Sources/Core/*.metal
  echo '"""#'
} > "$GEN"

SOURCES=("$ROOT"/Sources/Core/*.swift "$GEN")

# ---------------------------------------------------------------------------
# 2. The .saver bundle (an MH_BUNDLE)
# ---------------------------------------------------------------------------
SAVER="$BUILD/$NAME.saver"
echo "==> compiling $NAME.saver"
rm -rf "$SAVER"
mkdir -p "$SAVER/Contents/MacOS" "$SAVER/Contents/Resources"

swiftc -O -wmo -target "$TARGET" \
  -module-name "${NAME}Saver" \
  -emit-library -Xlinker -bundle \
  -framework ScreenSaver -framework MetalKit -framework Metal -framework AppKit \
  -o "$SAVER/Contents/MacOS/$NAME" \
  "${SOURCES[@]}" "$ROOT"/Sources/Saver/*.swift

cat > "$SAVER/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>$NAME</string>
    <key>CFBundleIdentifier</key><string>dev.kevin.saver.backrooms</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>$NAME</string>
    <key>CFBundlePackageType</key><string>BNDL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1.0</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>NSPrincipalClass</key><string>$CLASS</string>
</dict>
</plist>
PLIST

codesign --force --sign - --timestamp=none "$SAVER" >/dev/null 2>&1

# ---------------------------------------------------------------------------
# 3. The development harness
# ---------------------------------------------------------------------------
echo "==> compiling backdev"
swiftc -O -wmo -target "$TARGET" \
  -module-name backdev \
  -framework MetalKit -framework Metal -framework AppKit \
  -o "$BUILD/backdev" \
  "${SOURCES[@]}" "$ROOT/Tools/main.swift"

# ---------------------------------------------------------------------------
# 4. Smoke test: load the bundle exactly as ScreenSaverEngine would
# ---------------------------------------------------------------------------
echo "==> verifying bundle"
swiftc -O -target "$TARGET" \
  -framework ScreenSaver -framework MetalKit -framework AppKit \
  -o "$BUILD/verify-bundle" \
  "$ROOT/Tools/VerifyBundle.swift"
"$BUILD/verify-bundle" "$SAVER"

# ---------------------------------------------------------------------------
# 5. Optional distributable: universal (arm64 + x86_64) binary, zipped
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "dist" ]]; then
  echo "==> compiling x86_64 slice"
  swiftc -O -wmo -target "x86_64-apple-macos13.0" \
    -module-name "${NAME}Saver" \
    -emit-library -Xlinker -bundle \
    -framework ScreenSaver -framework MetalKit -framework Metal -framework AppKit \
    -o "$BUILD/$NAME-x86_64" \
    "${SOURCES[@]}" "$ROOT"/Sources/Saver/*.swift
  lipo -create "$SAVER/Contents/MacOS/$NAME" "$BUILD/$NAME-x86_64" \
       -output "$SAVER/Contents/MacOS/$NAME.universal"
  mv "$SAVER/Contents/MacOS/$NAME.universal" "$SAVER/Contents/MacOS/$NAME"
  rm -f "$BUILD/$NAME-x86_64"
  codesign --force --sign - --timestamp=none "$SAVER" >/dev/null 2>&1
  lipo -info "$SAVER/Contents/MacOS/$NAME"
  ditto -c -k --keepParent "$SAVER" "$BUILD/$NAME.saver.zip"
  echo "==> wrote $BUILD/$NAME.saver.zip"
fi

# ---------------------------------------------------------------------------
# 6. Optional install
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "install" ]]; then
  mkdir -p "$INSTALL_DIR"
  rm -rf "$INSTALL_DIR/$NAME.saver"
  cp -R "$SAVER" "$INSTALL_DIR/"
  echo "==> installed $INSTALL_DIR/$NAME.saver"
  echo "    Select it in System Settings > Screen Saver (under 'Other')."
fi
